FROM node:alpine

COPY . /server

RUN npm install 

EXPOSE 4000

ENV AWS_S3_ACCESS_KEY=AKIATS7DJBGFNYOAC347
ENV AWS_S3_ACCESS_SECRETE_KEY=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
ENV AWS_S3_BUCKET_NAME=presento-app
ENV AWS_S3_REGION=us-east-1
ENV AWS_S3_BUCKET_DOMAIN=https://presento-app.s3.amazonaws.com


CMD [ "npm", "start" ]
